server {
    listen 80;

    access_log off;
    error_log /dev/null;

    location / {
        root /app/frontend;
        index index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:18080;
    }
}
